<a href="https://colab.research.google.com/github/ashkanmulla/Ashkan_Data_Science_Practice/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lst_data = list(range(1, 11))
print(lst_data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
np.array(lst_data)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
e = np.array([lst_data])

In [ ]:
print(e.shape)
print(e.ndim)
print(e)

(1, 10)
2
[[ 1  2  3  4  5  6  7  8  9 10]]


In [ ]:
np1 = np.array(lst_data)

In [ ]:
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(type(np1))

<class 'numpy.ndarray'>


### Shape

In [ ]:
np1.shape

(10,)

In [ ]:
np1.ndim

1

### Create a multi-dimensinal array

In [ ]:
my_matrix = [[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]]

In [ ]:
md_arr = np.array(my_matrix)

In [ ]:
md_arr

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [ ]:
md_arr.shape

(3, 4)

In [ ]:
md_arr.ndim

2

In [ ]:
md_arr.dtype

dtype('int32')

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5], dtype=float)

In [ ]:
arr1

array([1., 2., 3., 4., 5.])

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
lst_odd_size = [[1, 2, 3], [4, 5], [7, 8, 9]]
lst_odd_size

[[1, 2, 3], [4, 5], [7, 8, 9]]

In [ ]:
md_arr_odd = np.array(lst_odd_size)

In [ ]:
md_arr_odd

array([list([1, 2, 3]), list([4, 5]), list([7, 8, 9])], dtype=object)

In [ ]:
md_arr_odd.shape

(3,)

In [ ]:
md_arr_odd.ndim

1

In [ ]:
md_arr_odd.dtype

dtype('O')

In [ ]:
my_list = [1, 2, 3, 4, 5, 6]

In [ ]:
arr1 = np.array(my_list, dtype='i')

In [ ]:
arr1

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [ ]:
arr1.shape

(6,)

In [ ]:
arr2 = arr1.reshape(3, 2)

In [ ]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [ ]:
arr2.ndim

2

In [ ]:
arr1

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [ ]:
arr3 = arr1.reshape(3, -1)

In [ ]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [ ]:
arr3.shape

(3, 2)

In [ ]:
my_list1 = list(range(1, 6))
my_list2 = list(range(10, 15))
my_list3 = list(range(20, 25))

In [ ]:
my_list1, my_list2, my_list3

([1, 2, 3, 4, 5], [10, 11, 12, 13, 14], [20, 21, 22, 23, 24])

In [ ]:
mul_arr = np.array([my_list1, my_list2, my_list3])

In [ ]:
mul_arr

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [ ]:
mul_arr.shape

(3, 5)

In [ ]:
mul_arr_15 = mul_arr.reshape(1, 15)

In [ ]:
mul_arr_15.shape

(1, 15)

In [ ]:
mul_arr_15.ndim

2

In [ ]:
mul_arr_51 = mul_arr_15.reshape(15, 1)

In [ ]:
mul_arr_51.shape

(15, 1)

In [ ]:
mul_arr_51.ndim

2

In [ ]:
mul_arr_15

array([[ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24]])

In [ ]:
mul_arr_51

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [10],
       [11],
       [12],
       [13],
       [14],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
a.ndim

1

In [ ]:
a.reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
b = a.reshape(6, 4, 1)

In [ ]:
b.ndim

3

In [ ]:
b

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23]]])

In [ ]:
c = a.reshape(3, 2, 4)

In [ ]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
x = np.array([1, 2, 3], dtype = np.int8)

In [ ]:
print(x.itemsize)

1


In [ ]:
x = np.array([1, 2, 3], dtype = np.int64)

In [ ]:
print(x.itemsize)

8


In [ ]:
x = np.array([1, 2, 3], dtype = np.int32)
print(x.itemsize)

4


In [ ]:
arr1 = np.arange(0, 11, 2)

In [ ]:
arr1

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
arr = np.random.randint(20, 30, 10)

In [ ]:
arr

array([20, 27, 28, 26, 25, 23, 22, 22, 26, 21])

In [ ]:
len(arr)

10

In [ ]:
# index starts with zero
arr[0]

20

In [ ]:
arr[5:8]

array([23, 22, 22])

In [ ]:
arr[:3]

array([20, 27, 28])

In [ ]:
arr[3:]

array([26, 25, 23, 22, 22, 26, 21])

In [ ]:
arr[-1]

21

In [ ]:
# Broadcasting
# Array slices are *actually* views on the original array
# That means, data isn't copied, and any modifications to the view would be reflected back to the source array

In [ ]:
arr

array([20, 27, 28, 26, 25, 23, 22, 22, 26, 21])

In [ ]:
arr[0:5] = 99

In [ ]:
arr

array([99, 99, 99, 99, 99, 23, 22, 22, 26, 21])

In [ ]:
new_arr = np.random.randint(10, 20, 10)

In [ ]:
new_arr

array([13, 11, 16, 13, 15, 12, 13, 17, 10, 16])

In [ ]:
slice_new_arr = new_arr[0:5]

In [ ]:
slice_new_arr

array([13, 11, 16, 13, 15])

In [ ]:
slice_new_arr[0] = 100

In [ ]:
slice_new_arr

array([100,  11,  16,  13,  15])

In [ ]:
new_arr

array([100,  11,  16,  13,  15,  12,  13,  17,  10,  16])

In [ ]:
slice_new_arr[:] = 111

In [ ]:
slice_new_arr

array([111, 111, 111, 111, 111])

In [ ]:
new_arr

array([111, 111, 111, 111, 111,  12,  13,  17,  10,  16])

In [ ]:
new_arr_copy = new_arr.copy()

In [ ]:
new_arr

array([111, 111, 111, 111, 111,  12,  13,  17,  10,  16])

In [ ]:
new_arr_copy

array([111, 111, 111, 111, 111,  12,  13,  17,  10,  16])

In [ ]:
new_arr_copy[0:5] = 123

In [ ]:
new_arr_copy

array([123, 123, 123, 123, 123,  12,  13,  17,  10,  16])

In [ ]:
new_arr

array([111, 111, 111, 111, 111,  12,  13,  17,  10,  16])

In [ ]:
a = list(range(1, 11))

In [ ]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
b = a[0:5]

In [ ]:
b

[1, 2, 3, 4, 5]

In [ ]:
b[0] = 100

In [ ]:
b

[100, 2, 3, 4, 5]

In [ ]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
b[0:3] = 123

TypeError: can only assign an iterable

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)

In [ ]:
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

In [ ]:
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
y

array([[5., 6.],
       [7., 8.]])

In [ ]:
x.ndim, y.ndim

(2, 2)

In [ ]:
x + y

array([[ 6.,  8.],
       [10., 12.]])

In [ ]:
x - y

array([[-4., -4.],
       [-4., -4.]])

In [ ]:
y - x

array([[4., 4.],
       [4., 4.]])

In [ ]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [ ]:
np.subtract(x, y)

array([[-4., -4.],
       [-4., -4.]])

In [ ]:
np.subtract(y, x)

array([[4., 4.],
       [4., 4.]])

In [ ]:
x * y

array([[ 5., 12.],
       [21., 32.]])

In [ ]:
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
y

array([[5., 6.],
       [7., 8.]])

In [ ]:
np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [ ]:
# dot product

In [ ]:
x.dot(y)

array([[19., 22.],
       [43., 50.]])

In [ ]:
x, y

(array([[1., 2.],
        [3., 4.]]),
 array([[5., 6.],
        [7., 8.]]))

In [ ]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [ ]:
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
print(np.sum(x)) # compute sum of all elements of the array

10.0


In [ ]:
print(np.sum(x, axis=0)) # compute sum of each column

[4. 6.]


In [ ]:
print(np.sum(x, axis=1)) # compute sum of each row

[3. 7.]


In [ ]:
arr = np.arange(15)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr = arr.reshape(3, 5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
np.max(arr)

14

In [ ]:
np.min(arr)

0

In [ ]:
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
y

array([[5., 6.],
       [7., 8.]])

In [ ]:
np.maximum(x, y)

array([[5., 6.],
       [7., 8.]])

In [ ]:
a = np.array([[1, 2], [2, 1]], dtype=np.float64)
b = np.array([[2, 1], [1, 2]], dtype=np.float64)

In [ ]:
np.maximum(a, b)

array([[2., 2.],
       [2., 2.]])

In [ ]:
np.minimum(a, b)

array([[1., 1.],
       [1., 1.]])

In [ ]:
a

array([[1., 2.],
       [2., 1.]])

In [ ]:
b

array([[2., 1.],
       [1., 2.]])

In [ ]:
zeros_a = np.zeros_like(a)

In [ ]:
zeros_a

array([[0., 0.],
       [0., 0.]])

In [ ]:
ones_a = np.ones_like(a)

In [ ]:
ones_a

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a

array([[1., 2.],
       [2., 1.]])

In [ ]:
i = 10

In [ ]:
print("Cell 1")

print("Cell 2")

print("Cell 3")

Cell 1
Cell 2
Cell 3


In [ ]:
ones_a

np.zeros((3, 3))

a

array([[1., 2.],
       [2., 1.]])

In [ ]:
a = np.array([[1, 2], [2, 1]], dtype=np.float64)
b = np.array([[2, 1], [1, 2]], dtype=np.float64)

np.maximum(a, b)

np.minimum(a, b)

a



b

array([[2., 1.],
       [1., 2.]])

In [ ]:
a = np.arange(24)
print(a)

a.ndim


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


1

In [ ]:
b = a.reshape(2, 4, 3)
b.ndim

3

In [ ]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
b[0][1][0]

3

In [ ]:
b[1][1][0]

15

In [ ]:
for x in range(0, 2):
    for y in range(0, 4):
        for z in range(0, 3):
            print(b[x][y][z])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [ ]:
c = a.reshape(2, 2, 3, 2)

In [ ]:
c

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [ ]:
c.ndim

4

In [ ]:
c[1][0][0][0]

12