<a href="https://colab.research.google.com/github/ashkanmulla/Ashkan_Data_Science_Practice/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import numpy as np

In [80]:
l1 = [1,2,3,4]

In [81]:
n1 = np.array(l1)

In [82]:
type(n1)

numpy.ndarray

In [83]:
n2 = np.array([[1,2,3,4],[4,3,2,1]])

In [84]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [85]:
type(n2)

numpy.ndarray

In [86]:
# Initializing Numpy array with zero

In [87]:
import numpy as np

In [88]:
n1 = np.zeros((1,2))

In [89]:
n1

array([[0., 0.]])

In [90]:
n1 = np.zeros((5,5))

In [91]:
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [92]:
n3 = np.zeros((2,3))

In [93]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
n4 = np.zeros((10,10))

In [95]:
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [96]:
#Initializing Numpy array with same number

In [97]:
n5 = np.full((3,3),55)

In [98]:
n5

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [99]:
 #Initializing Numpy array within a range

In [100]:
n6 = np.arange(10,20)

In [101]:
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [102]:
import numpy as np

In [103]:
n1 = np.arange(50,200,2)

In [104]:
n1

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100,
       102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
       128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152,
       154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178,
       180, 182, 184, 186, 188, 190, 192, 194, 196, 198])

In [105]:
#Initializing Numpy array with random number

In [106]:
import numpy as np

In [107]:
n1 = np.random.randint(1,5)

In [108]:
n1

1

In [109]:
n1 = np.random.randint(1,100,5)

In [110]:
n1

array([43, 73, 50, 84, 23])

In [111]:
#Checking & changing the shape of Numpy arrays

In [112]:
import numpy as np

In [113]:
n1 = np.array([[1,2,3],[4,5,6]])

In [114]:
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
n1.shape

(2, 3)

In [116]:
n1.shape = (3,2)

In [117]:
n1.shape

(3, 2)

In [118]:
import numpy as np

In [119]:
n7 = np.array([[1,2,3,4,5],[5,4,3,2,1]])

In [120]:
n7

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [121]:
#Joining Numpy Arrays (Vertical , Horizontal and Column Stack)

In [122]:
import numpy as np

In [123]:
n1 = np.array([1,2,3])

In [124]:
n2 = np.array([4,5,6])

In [125]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [127]:
np.column_stack((n1,n2)) #Remember

array([[1, 4],
       [2, 5],
       [3, 6]])

In [128]:
#Intersection & Difference n1 - n2 likhna h second wale me ok

In [133]:
import numpy as np

In [135]:
n1 = np.array([10,20,30,40,50,60])

In [136]:
n2 = np.array([50,60,70,80,90])

In [140]:
np.intersect1d(n1,n2)

array([50, 60])

In [143]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [144]:
np.setdiff1d(n2,n1)

array([70, 80, 90])