<a href="https://colab.research.google.com/github/ashkanmulla/Ashkan_Data_Science_Practice/blob/main/Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a', 'b', 'c']
lst_data = [10, 20, 30]

In [3]:
s_lst_data = pd.Series(lst_data)

In [5]:
s_lst_data_label = pd.Series(lst_data, index=labels)

In [6]:
s_lst_data_label

a    10
b    20
c    30
dtype: int64

In [7]:
s_lst_data_label.index

Index(['a', 'b', 'c'], dtype='object')

In [8]:
arr = np.array([11, 22, 33])

In [9]:
arr

array([11, 22, 33])

In [10]:
s_arr_labels = pd.Series(arr, labels)

In [11]:
s_arr_labels

a    11
b    22
c    33
dtype: int64

In [12]:
d = {'a': "41", "b": 51, "c": 61}

In [13]:
pd.Series(d)

a    41
b    51
c    61
dtype: object

In [14]:
d = {"India": "Delhi", "Srilanka": "Colombo", "Australia": "Sydney"}

In [15]:
pd.Series(d)

India          Delhi
Srilanka     Colombo
Australia     Sydney
dtype: object

In [16]:
pd.Series(d, labels)

a    NaN
b    NaN
c    NaN
dtype: object

In [17]:
labels = ['a', 'b', 'a']
lst_data = [10, 20, 30]

In [18]:
pd.Series(lst_data, labels)

a    10
b    20
a    30
dtype: int64

In [19]:
d = {"India": "Delhi", "Srilanka": "Colombo", "a": "Sydney"}

In [20]:
s1 = pd.Series(d, labels)

In [21]:
s1

a    Sydney
b       NaN
a    Sydney
dtype: object

In [22]:
s1["a"]

a    Sydney
a    Sydney
dtype: object

In [23]:
s_example = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [24]:
s_example

d    4
b    7
a   -5
c    3
dtype: int64

In [25]:
s_example.values

array([ 4,  7, -5,  3])

In [26]:
s_example.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [27]:
s_example['d']

4

In [28]:
s_example['d'] = 100

In [29]:
s_example

d    100
b      7
a     -5
c      3
dtype: int64

In [30]:
s_example > 0

d     True
b     True
a    False
c     True
dtype: bool

In [31]:
s_example[s_example > 0]

d    100
b      7
c      3
dtype: int64

In [32]:
# in

In [33]:
"d" in s_example

True

In [34]:
100 in s_example

False

In [35]:
100 in s_example.values

True

In [36]:
s_example.values

array([100,   7,  -5,   3])